export const METRICS = [
    { key: "normalized_impact", label: "Impacto Normalizado*" },
    { key: "excel_lider", label: "Excelencia con Liderazgo" },
    { key: "output", label: "Producción Científica" },
    { key: "lider", label: "Liderazgo Científico" },
    { key: "not_own_journals_output", label: "Revistas Externas" },
    { key: "own_journals", label: "Revistas Propias" },
    { key: "excel", label: "Excelencia" },
    { key: "q1", label: "Q1" },
    { key: "colab", label: "Colaboración Internacional" },
    { key: "open_access", label: "Acceso Abierto*" },
    { key: "stp", label: "Talento Científico" },
    { key: "ik", label: "Conocimiento Innovador" },
    { key: "patents", label: "Patentes" },
    { key: "tech_impact", label: "Impacto Tecnológico*" },
    { key: "AM", label: "Altmetrics" },
    { key: "sdg", label: "ODS" },
    { key: "female_stp", label: "Talento Científico Femenino" },
    { key: "overton", label: "Políticas Públicas" },
  ];