export const METRICS = [
    { key: "normalized_impact", label: "Impacto Normalizado* (13%)" },
    { key: "excel_lider", label: "Excelencia con Liderazgo (8%)" },
    { key: "output", label: "Producción Científica (8%)" },
    { key: "lider", label: "Liderazgo Científico (5%)" },
    { key: "not_own_journals_output", label: "Revistas Externas (3%)" },
    { key: "own_journals", label: "Revistas Propias (3%)" },
    { key: "excel", label: "Excelencia (2%)" },
    { key: "q1", label: "Q1 (2%)" },
    { key: "colab", label: "Colaboración Internacional (2%)" },
    { key: "open_access", label: "Acceso Abierto* (2%)" },
    { key: "stp", label: "Talento Científico (2%)" },
    { key: "ik", label: "Conocimiento Innovador (10%)" },
    { key: "patents", label: "Patentes (10%)" },
    { key: "tech_impact", label: "Impacto Tecnológico* (10%)" },
    { key: "AM", label: "Altmetrics (3%)" },
    { key: "sdg", label: "ODS (3%)" },
    { key: "female_stp", label: "Talento Científico Femenino (3%)" },
    { key: "overton", label: "Políticas Públicas (3%)" },
  ];